#!/usr/bin/env node
'use strict';

// âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
//  Skynet Protocol â First-Time Setup
//  Run: node setup.js
//  Creates the DB, generates an admin token, and optionally mints the first
//  Overmind token. Copy the output into your .env file.
// âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

const crypto = require('crypto');
const path   = require('path');
const fs     = require('fs');

// Bootstrap DB
const { initDatabase, db } = require('./database');
initDatabase();

// Generate admin token
const adminToken = 'snadmin_' + crypto.randomBytes(32).toString('hex');

// Generate first Overmind token if a name was passed
const overmindName = process.argv[2];
let overmindToken  = null;

if (overmindName) {
  overmindToken = 'snmcp_' + crypto.randomBytes(32).toString('hex');
  db.prepare(
    'INSERT OR IGNORE INTO tokens (token, overmind_name, label) VALUES (?, ?, ?)'
  ).run(overmindToken, overmindName, 'Initial token â generated by setup.js');
  console.log(`â Token created for Overmind: ${overmindName}`);
}

// Write .env file (never overwrite if it exists)
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  let envContent = `# Skynet Protocol â environment config\n`;
  envContent    += `PORT=3001\n`;
  envContent    += `ADMIN_TOKEN=${adminToken}\n`;
  if (overmindToken) {
    envContent += `# First Overmind token (${overmindName})\n`;
    envContent += `# OVERMIND_TOKEN=${overmindToken}\n`;
  }
  fs.writeFileSync(envPath, envContent);
  console.log('â .env file created');
} else {
  console.log('â¹ï¸  .env already exists â not overwritten');
}

console.log('');
console.log('âââââââââââââââââââââââââââââââââââââââââââââââââ');
console.log('  SKYNET SETUP COMPLETE â Save these values');
console.log('âââââââââââââââââââââââââââââââââââââââââââââââââ');
console.log('');
console.log('ADMIN_TOKEN (for token management):');
console.log(' ', adminToken);
console.log('');
if (overmindToken) {
  console.log(`OVERMIND TOKEN (for ${overmindName}):`);
  console.log(' ', overmindToken);
  console.log('');
  console.log('Claude Code config (add to ~/.claude.json mcpServers):');
  console.log('');
  console.log(JSON.stringify({
    [overmindName.toLowerCase().replace(/\s+/g, '-')]: {
      command:     'node',
      args:        [path.join(__dirname, 'skynet-bridge.mjs')],
      env: {
        SKYNET_URL:   'http://YOUR_SERVER_HOST:3001',
        SKYNET_TOKEN: overmindToken,
      },
    },
  }, null, 2));
  console.log('');
}
console.log('âââââââââââââââââââââââââââââââââââââââââââââââââ');
console.log('');
console.log('Usage: node setup.js [overmind_name]');
console.log('Example: node setup.js "T-Bot"');
console.log('');
